# Generated by Django 4.1.5 on 2023-02-09 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("User", "0001_initial"),
        ("Cafe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=80)),
                ("content", models.CharField(max_length=1000)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="review_images/%Y%m%d"),
                ),
                ("star", models.IntegerField()),
                ("mark", models.BooleanField()),
                (
                    "cafe_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cafe_id",
                        to="Cafe.cafe",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Review_user",
                        to="User.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_id",
                        to="Review.review",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ReviewLike_user",
                        to="User.users",
                    ),
                ),
            ],
        ),
    ]
