# Generated by Django 4.1.7 on 2023-02-14 11:00

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=80)),
                ('content', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='review_images/%Y%m%d')),
                ('star', models.IntegerField()),
                ('mark', models.BooleanField()),
                ('keywords', multiselectfield.db.fields.MultiSelectField(choices=[('데이트', '데이트'), ('작업하기 좋은', '작업하기 좋은'), ('공부하기 좋은', '공부하기 좋은'), ('조용한', '조용한'), ('시끌벅적한', '시끌벅적한'), ('의자가 편한', '의자가 편한'), ('디저트 맛있는', '디저트 맛있는'), ('커피가 맛있는', '커피가 맛있는'), ('저렴한', '저렴한'), ('친절한', '친절한'), ('혼카페', '혼카페'), ('장소가 넓은', '장소가 넓은'), ('콘센트가 많은', '콘센트가 많은'), ('화장실 깨끗한', '화장실 깨끗한'), ('인테리어 예쁜', '인테리어 예쁜')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_id', to='Review.review')),
            ],
        ),
    ]
