# Generated by Django 4.1.6 on 2023-02-10 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Cafe", "0002_initial"),
        ("Review", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewlike",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ReviewLike_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="cafe_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cafe_id",
                to="Cafe.cafe",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Review_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
