# Generated by Django 4.1.5 on 2023-02-09 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Cafe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField()),
                ("username", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=16)),
                ("email", models.CharField(max_length=16)),
                (
                    "location_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="location_id",
                        to="Cafe.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_address", models.CharField(max_length=32)),
                ("users_id", models.CharField(max_length=16)),
                ("password", models.CharField(max_length=16)),
                ("realname", models.CharField(max_length=20)),
                ("nickname", models.CharField(max_length=24)),
                ("verified", models.IntegerField(default=0)),
                (
                    "school_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="school_id",
                        to="User.school",
                    ),
                ),
            ],
        ),
    ]
