# Generated by Django 4.1.6 on 2023-02-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longtitude',
        ),
        migrations.AddField(
            model_name='cafe',
            name='average_star',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cafe',
            name='latitude',
            field=models.FloatField(default=37.314964),
        ),
        migrations.AddField(
            model_name='cafe',
            name='longtitude',
            field=models.FloatField(default=126.575308),
        ),
    ]
