# Generated by Django 4.1.6 on 2023-02-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='average_star',
            field=models.FloatField(default=0),
        ),
    ]
