# Generated by Django 4.1.7 on 2023-02-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='average_star',
            field=models.IntegerField(default=0),
        ),
    ]
