# Generated by Django 4.1.7 on 2023-02-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0003_cafe_average_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='average_star',
            field=models.FloatField(default=0),
        ),
    ]
