# Generated by Django 4.1.5 on 2023-02-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cafe', '0004_alter_cafe_average_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='review_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
